parameters:
    stageName: ''
    environmentName: ''
    feedCredential: ''
    feedUrl: ''

stages:
- stage: ${{ parameters.stageName }}
  displayName: Release Microsoft.PowerShell.MarkdownRender to '${{ parameters.stageName }}'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))

  jobs:
  - deployment: Publish_${{ parameters.stageName }}
    displayName: Release to Feed
    pool:
      vmImage: windows-latest

    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: nuget

          - powershell: |
              Get-ChildItem -Recurse "$(Pipeline.Workspace)/nuget"
            displayName: Capture downloaded artifact

          - powershell: |
              Copy-Item "$(Pipeline.Workspace)/nuget/Microsoft.PowerShell.MarkdownRender.*.nupkg" -Destination "$(Build.ArtifactStagingDirectory)" -Force
              Get-ChildItem "$(Build.ArtifactStagingDirectory)/Microsoft.PowerShell.MarkdownRender.*.nupkg"
            displayName: 'Copy and Capture NuGet package'

          - task: NuGetAuthenticate@0
            condition: ne('${{ parameters.feedUrl }}', '')

          - powershell: |
              nuget push -ApiKey AzureArtifacts -source '${{ parameters.feedUrl }}' '$(Build.ArtifactStagingDirectory)/Microsoft.PowerShell.MarkdownRender.*.nupkg'
            displayName: Push to internal feed
            condition: ne('${{ parameters.feedUrl }}', '')

          - task: NuGetCommand@2
            displayName: 'NuGet push'
            inputs:
              command: push
              packagesToPush: '$(Build.ArtifactStagingDirectory)/Microsoft.PowerShell.MarkdownRender.*.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: ${{ parameters.feedCredential }}
              condition: eq('${{ parameters.feedUrl }}', '')
